
font: 
  normal:
    family: JetBrains Mono Nerd Font
    style: Regular #Nerd Font Complete
  bold:
    family: JetBrains Mono Nerd Font
    style: Bold #Nerd Font Complete Mono
  italic:
    family: JetBrains Mono Nerd Font
    style: Italic #Nerd Font Complete

  offset:
    x: 0
    y: 1
  glyph_offset:
    x: 0
    y: 0
